Add conda support for configure script

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,23 +9,65 @@ curl --silent https://plausible.benparks.net/flask-plausible/bpcells-configure >
 
 # Test compiling a simple hdf5 program to check for compatibility
 CC=$("${R_HOME}/bin/R" CMD config CC)
-HDF5_NOT_FOUND_MSG="Unable to locate libhdf5. Please install manually or edit compiler flags."
 
+echo "Testing hdf5 by compiling example program..."
+
+# Vanilla install test
 HDF5_CFLAGS=""
 HDF5_LIBS="-lhdf5"
-if ! $CC tools/h5write.c $HDF5_CFLAGS $HDF5_LIBS -o tools/h5write 2> /dev/null; then
-    # Next we optimistically try using pkg-config and retry the test compile
-    HDF5_CFLAGS="$(pkg-config hdf5 --cflags 2>/dev/null)"
-    HDF5_LIBS="$(pkg-config hdf5 --libs 2>/dev/null)"
-    if ! $CC tools/h5write.c $HDF5_CFLAGS $HDF5_LIBS -o tools/h5write 2> /dev/null; then
-        # If we fail after pkg-config, just give up
-        echo $HDF5_NOT_FOUND_MSG
-        exit 1
+HDF5_OK=""
+$CC tools/h5write.c $HDF5_CFLAGS $HDF5_LIBS -o tools/h5write 2>/dev/null && HDF5_OK="yes";
+
+# pkg-config flags
+if [ -z $HDF5_OK ]; then
+    printf "\n\nRetrying with pkg-config flags...\n"
+    if HDF5_CFLAGS="$(pkg-config hdf5 --cflags 2>/dev/null)" && \
+        HDF5_LIBS="$(pkg-config hdf5 --libs 2>/dev/null)"; then
+        $CC tools/h5write.c $HDF5_CFLAGS $HDF5_LIBS -o tools/h5write && HDF5_OK="yes";
+    else
+        echo "Error running 'pkg-config hdf5 --cflags --libs'"
     fi
 fi
- 
+
+# conda env
+if [ -z $HDF5_OK ]; then
+    printf "\n\nSearching for hdf5 in a conda env...\n"
+    if [ -z "$CONDA_PREFIX" ] ; then
+        echo "no conda environment found in '\$CONDA_PREFIX'"
+    else
+        HDF5_CFLAGS="-I$CONDA_PREFIX/include"
+        HDF5_LIBS="-Wl,-rpath,$CONDA_PREFIX/lib -L$CONDA_PREFIX/lib -lhdf5"
+        $CC tools/h5write.c $HDF5_CFLAGS $HDF5_LIBS -o tools/h5write && HDF5_OK="yes";
+    fi
+fi
+
+if [ -z $HDF5_OK ]; then
+    printf "\n\nUnable to locate libhdf5. Please install manually or edit compiler flags.\n"
+    exit 1
+fi
+
+echo "Found working hdf5"
+echo "HDF5_CFLAGS='${HDF5_CFLAGS}'"
+echo "HDF5_LIBS='${HDF5_LIBS}'"
+
+
+
+ARCH_FLAG="-march=native"
+printf "\nTesting architecture flag support support..."
+ARCH_CANDIDATES=("-march=native" "")
+for ARCH_FLAG in "${ARCH_CANDIDATES[@]}"; do
+    if $CC tools/h5write.c $ARCH_FLAG $HDF5_CFLAGS $HDF5_LIBS -o tools/h5write 2>/dev/null; then
+        printf "'%s' succeeded\n" $ARCH_FLAG
+        break;
+    else
+        printf "'%s' failed..." $ARCH_FLAG
+    fi
+done
+echo "ARCH_FLAG='$ARCH_FLAG'"
+
 # Make substitutions in Makevars.in
 sed \
     -e "s|%HDF5_CFLAGS%|${HDF5_CFLAGS}|g" \
     -e "s|%HDF5_LIBS%|${HDF5_LIBS}|g" \
+    -e "s|%ARCH_FLAG%|${ARCH_FLAG}|g" \
     src/Makevars.in > src/Makevars
