Add check for C++17 std::filesystem

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,11 @@ curl --silent https://plausible.benparks.net/flask-plausible/bpcells-configure >
 
 # Test compiling a simple hdf5 program to check for compatibility
 CC=$("${R_HOME}/bin/R" CMD config CC)
+CXX=$("${R_HOME}/bin/R" CMD config CXX)
+
+############################
+# HDF5 compatibility check
+############################
 
 echo "Testing hdf5 by compiling example program..."
 
@@ -50,7 +55,9 @@ echo "Found working hdf5"
 echo "HDF5_CFLAGS='${HDF5_CFLAGS}'"
 echo "HDF5_LIBS='${HDF5_LIBS}'"
 
-
+############################
+# Arch flag check
+############################
 
 ARCH_FLAG="-march=native"
 printf "\nTesting architecture flag support support..."
@@ -64,9 +71,28 @@ for ARCH_FLAG in "-march=native" ""; do
 done
 echo "ARCH_FLAG='$ARCH_FLAG'"
 
+############################
+# C++17 filesystem check
+############################
+CXX17_OK=""
+CXX_FS_FLAG=""
+$CXX tools/cxx17_filesystem.cc -std=c++17 $CXX_FS_FLAG -o tools/cxx17_filesystem 2>/dev/null && CXX17_OK="yes";
+if [ -z $CXX17_OK ]; then
+    CXX_FS_FLAG="-lstdc++fs"
+    $CXX tools/cxx17_filesystem.cc -std=c++17 $CXX_FS_FLAG -o tools/cxx17_filesystem 2>/dev/null && CXX17_OK="yes";
+    if [ ! -z $CXX17_OK ]; then
+        printf "\nUsed fallback compatibility flags for C++17 std::filesystem support: $CXX_FS_FLAG\n"
+    fi
+fi
+if [ -z $CXX17_OK ]; then
+    printf "\n\nUnable to compile program with C++17 std::filesystem.\nPlease install a newer compiler version and set CC and CXX in ~/.R/Makevars\n"
+    exit 1
+fi
+
 # Make substitutions in Makevars.in
 sed \
     -e "s|%HDF5_CFLAGS%|${HDF5_CFLAGS}|g" \
     -e "s|%HDF5_LIBS%|${HDF5_LIBS}|g" \
     -e "s|%ARCH_FLAG%|${ARCH_FLAG}|g" \
+    -e "s|%CXX_FS_FLAG%|${CXX_FS_FLAG}|g" \
     src/Makevars.in > src/Makevars
