[r] Fix `libhwy` detection (#240)

diff --git a/r/configure b/r/configure
--- a/r/configure
+++ b/r/configure
@@ -158,21 +158,23 @@ printf "\nTesting availability of highway SIMD library..."
 HWY_OK=""
 HWY_CFLAGS="-Ibpcells-cpp"
 HWY_LIBS="-lhwy"
-$CXX tools/hwy-test.cpp $CXXFLAGS $LDFLAGS 2>&3 && HWY_OK="yes";
+$CXX tools/hwy-test.cpp $CXXFLAGS $LDFLAGS $HWY_CFLAGS $HWY_LIBS 2>&3 && HWY_OK="yes";
 if [ -z $HWY_OK ]; then
     if [ ! -f tools/highway/lib/libhwy.a ]; then
         printf "\nBuilding highway SIMD library from source\n"
         CXX=$CXX bash src/vendor/highway/manual-build/build_highway.sh src/vendor/highway tools/highway && HWY_OK="yes";
+        if [ -z $HWY_OK ]; then
+            printf "\n\nUnable to build highway SIMD library from source\n"
+            exit 1
+        fi
     else
         printf "\nUsing cached highway build\n"
         HWY_OK="yes"
     fi
     HWY_CFLAGS="$HWY_CFLAGS -I../tools/highway/include"
     HWY_LIBS="-L../tools/highway/lib -lhwy"
-fi
-if [ -z $CXX17_OK ]; then
-    printf "\n\nUnable to build highway SIMD library from source\n"
-    exit 1
+else
+    printf "\nFound working highway SIMD library\n"
 fi
 
 # Make substitutions in Makevars.in
